# Generated by Django 5.0.2 on 2024-02-14 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("owner", models.CharField(max_length=20)),
                (
                    "value",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "1"),
                            (2, "2"),
                            (3, "3"),
                            (5, "5"),
                            (8, "8"),
                            (13, "13"),
                            (20, "20"),
                            (40, "40"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="core.room",
                    ),
                ),
            ],
        ),
    ]
