version: "3.9"
name: planningpoker

# Project services composition
services:

  # Database composition
  database:
    build:
      context: ../database
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

  # Redis composition
  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379

  # Backend composition
  backend:
    build:
      context: ../backend
      args:
        - DEV=true
    volumes:
      - ../backend/app:/app
    ports:
      - ${API_PORT}:8000
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=database
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
      - DEBUG=1
    depends_on:
      - redis
      - database

  # Frontend composition
  frontend:
    build:
      context: ../frontend
    volumes:
      - '../frontend/app:/app'
      - '/app/node_modules'
      - '/app/.next'
    ports:
      - 3000:3000
    command: >
      sh -c "npm run dev"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NEXT_PUBLIC_API_HOST=${API_HOST}
      - NEXT_PUBLIC_API_PORT=${API_PORT}

# Composition volumes
volumes:
  db-data:
